name: Deploy

on:
  pull_request:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 19.x
      - name: Build
        run: |
          echo npm i -g npm-check-updates
          echo ncu 
          echo ncu -u 
          echo cat package-lock.json
          echo ncu doc
          echo ncu --doctor -u
          echo npm install
          npm install --force
          echo npm build
          npm run build 
