name: Deploy

on:
  pull_request:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 19.x
      - name: Build
        run: |
          npm install -g npm-check
          npm-check
          npm-check -u
          npm ci
          npm run build
