# This is a basic workflow to help you get started with Actions

name: Create Post from Issue

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  issues:
    types: [opened, edited, milestoned]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 dump:
  runs-on: ubuntu-latest
  steps:
  - name: $github
    run: echo ${{ github.event.comment.body }} && echo "$GITHUB_CONTEXT"
    env:
     GITHUB_CONTEXT: ${{ toJson(github) }}

