# This is a basic workflow to help you get started with Actions

name: Create Post from Issue

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  issues:
    types: [opened, edited]
#   issue_comment:
#     types: [edited]
#   pull_request:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 create-post:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v1
   - name: check for changes
     run: |
       git config --global user.name "GitHub Action"
       git config --global user.email "action@github.com"
       
       export DIRNAME=`echo "$(date +'%Y %m %d') ${{ github.event.issue.title }}" | iconv -t ascii//TRANSLIT | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z`
       export POSTURL=`echo "/blog/${{ github.event.issue.title }}" | iconv -t ascii//TRANSLIT | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z`
       echo $DIRNAME
       git checkout $DIRNAME || git checkout -b $DIRNAME
       mkdir src/posts/$DIRNAME
       echo "---" > src/posts/$DIRNAME/index.md
       echo "layout: post" >> src/posts/$DIRNAME/index.md
       echo "path: '$POSTURL'" >> src/posts/$DIRNAME/index.md
       echo "title: ${{ github.event.issue.title }}" >> src/posts/$DIRNAME/index.md
       echo "date: $(date +'%Y-%m-%d')" >> src/posts/$DIRNAME/index.md
       echo "---" >> src/posts/$DIRNAME/index.md
       echo "${{ github.event.issue.body }}" >> src/posts/$DIRNAME/index.md
       git add -A
       git commit -m added-post
       echo "@@@"
       cat src/posts/$DIRNAME/index.md
       echo "Sharing branch name to next actions according to https://stackoverflow.com/a/57969570 ..."
       echo "DIRNAME=$DIRNAME" >> $GITHUB_ENV

   - name: Push changes
     uses: ad-m/github-push-action@master
     with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ env.DIRNAME }}
        
   - name: Create Pull Request
     uses: peter-evans/create-pull-request@v3
     with:
       base: master
       branch: ${{ env.DIRNAME }}
