# This is a basic workflow to help you get started with Actions

name: Create Post from Issue

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  issues:
    types: [edited, labeled]
#   issue_comment:
#     types: [edited]
#   pull_request:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 create-post:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v1
   - name: check for changes
     run: |
       [ "${{ github.even.issue.author_association }}" == "OWNER" ] && exit 1
       git config --global user.name "GitHub Action"
       git config --global user.email "action@github.com"
       export TS=`echo "${{ gitHub.event.issue.created_at }}" | head -c 10`
       export DIRNAME=`echo "$TS ${{ github.event.issue.title }}" | iconv -t ascii//TRANSLIT | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z`
       export POSTURL=`echo "${{ github.event.issue.title }}" | iconv -t ascii//TRANSLIT | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z`
       export PRNAME=`echo "$TS ${{ github.event.issue.title }}"`
       export EXCERPT=`echo "${{ github.event.issue.body }}" | head -1`
       export MEAT=`echo "${{ github.event.issue.body }}" | tail -n +2`
       echo $DIRNAME
       git checkout $DIRNAME || git checkout -b $DIRNAME
       mkdir -p src/posts/$DIRNAME
       echo "---" > src/posts/$DIRNAME/index.md
       echo "layout: post" >> src/posts/$DIRNAME/index.md
       echo "path: '/blog/$POSTURL'" >> src/posts/$DIRNAME/index.md
       echo "title: ${{ github.event.issue.title }}" >> src/posts/$DIRNAME/index.md
       echo "date: '$TS'" >> src/posts/$DIRNAME/index.md
       echo "tag: ${{ github.event.issue.labels[0].name }}" >> src/posts/$DIRNAME/index.md
       echo "tag_color: ${{ github.event.issue.labels[0].description }}" >> src/posts/$DIRNAME/index.md
       echo "$EXCERPT" >> src/posts/$DIRNAME/index.md
       echo "---" >> src/posts/$DIRNAME/index.md
       echo "$MEAT" >> src/posts/$DIRNAME/index.md
       echo " " >> src/posts/$DIRNAME/index.md
       echo "---" >> src/posts/$DIRNAME/index.md
       echo "[Comment on this post in GitHub](${{ github.event.issue.html_url }})" >> src/posts/$DIRNAME/index.md

       git add -A
       git commit -m added-post
       echo "@@@"
       cat src/posts/$DIRNAME/index.md
       echo "Sharing branch name to next actions according to https://stackoverflow.com/a/57969570 ..."
       echo "DIRNAME=$DIRNAME" >> $GITHUB_ENV
       echo "PRNAME=$PRNAME" >> $GITHUB_ENV

   - name: Push changes
     uses: ad-m/github-push-action@master
     with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ env.DIRNAME }}
        
   - name: pull-request
     uses: repo-sync/pull-request@v2
     with:
        destination_branch: "master"
        source_branch: ${{ env.DIRNAME }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: ${{ env.PRNAME }}

   - name: $github
     run: echo "$GITHUB_CONTEXT"
     env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
